### PR TITLE
Facelift on the homepage

### PR DESCRIPTION
**Pull request by staltz**
I had to improve the homepage to be more attractive for website visitors.

**Before**
screen shot 2017-02-14 at 19 23 48

**After**
screen shot 2017-02-14 at 19 23 54

PS: I know I used the Cycle.js logo, not the CycleConf logo. It turns out it was very hard to get a nice background picture to match the CycleConf logo, so in the meanwhile, let's use the original Cycle logo. Of course we can improve the homepage later too.

@festinalent3 What do you say? :)

### CODE REVIEW

**Comment by festinalent3** [comment]
Love it! 👍 😄  Only remark; is it possible to vertically center the content? Also maybe decrease the line spacing in the paragraph?

**Comment by festinalent3** [comment]
And also because I'm an asshole; what about decreasing the brightness of the backfround picture just slightly?

**Comment by staltz** [comment]
When I find some time (later today), sure. What about the logo? Should it be centered?

**Comment by staltz** [comment]
How about now?

screen shot 2017-02-15 at 22 52 04

**Comment by festinalent3** [comment]
Looks great @staltz ! 👍

**Pull request merged**
